services:
  - type: web
    name: aimkill-key-manager
    env: node
    plan: free
    region: oregon
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: OWNER_ID
        sync: false
      - key: BOT_API_KEY
        value: bot_br_live_9f733b9de44c9751167f40c2
      - key: WEB_URL
        value: https://br-auth-all-panels.vercel.app/
